name: Quality&Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  LANG: ru_RU.UTF-8

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.3-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: bot_test
          POSTGRES_USER: bot
          POSTGRES_PASSWORD: password
    env:
      DATABASE_URL: "postgres://bot:password@localhost:5432/bot_test"
    steps:
    - uses: actions/checkout@v2
    - name: Set up locale
      run: |
        sudo locale-gen ru_RU.UTF-8
        sudo update-locale LANG=ru_RU.UTF-8
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install flake8
        pip install -r tests/requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics --exclude handlers/__init__.py
    - name: Test with pytest
      run: |
        pytest --cov-report=xml --cov=. tests/
      env:
        API_BOT_TOKEN: ${{ secrets.API_BOT_TOKEN }}
        OWM_TOKEN: ${{ secrets.OWM_TOKEN }}
        WEBHOOK: ${{ secrets.WEBHOOK }}
        VK_SERVICE_TOKEN: ${{ secrets.VK_SERVICE_TOKEN }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        directory: ./coverage/reports/
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: false
